### ISSUE TITLE
userdata

### ISSUE THREAD

**Issue by martinwells** [illandril/box2dweb-closure#1]
Wondering why you removed the get/setUserData functionality

**Comment by illandril** [comment]
Personal preference. Since it is very easy to modify the prototype of a Javascript object at any time, I'd rather actively add a properly typed variable for any UserData than use the generic getter and setter.

**Comment by martinwells** [comment]
Aaah, gotcha. Thanks. Good choice.

**Comment by martinwells** [comment]
Actually, now that I think about it. Maybe not a great idea. Whilst it doesn't have much of an impact, isn't it better to stay compliant to the original API as much as possible?

**Comment by illandril** [comment]
It's all a matter of opinion really...
On one hand, it makes it easier for somebody to port things from a different language to Javascript.
On the other hand, it encourages people to use better practices for Javascript.

If somebody wants to use UserData, they can always add it back in.
If I hear a lot of requests to add it back into my fork, then I might, but until then I'm going to stick with the "whatever works best for me" approach (especially considering that I don't know of any projects actually using this fork other than my own not-very-active ones).

**Comment by martinwells** [comment]
Yep. Completely understand.
