### ISSUE TITLE
Revolute joint motors with mass

### ISSUE THREAD

**Issue by martinwells** [illandril/box2dweb-closure#2]
Can't seem to get a revolute joint to move it's motor is the objects its attached to have mass. Anybody seen anything similar?

**Comment by illandril** [comment]
I did have a similar issue at one point, and found out I was missing something... I don't remember what it was though. If you have a simple test case to reproduce the issue, I might be able to put in some time to investigate it.

**Comment by martinwells** [comment]
Yeah. I figured it out. m_I inertia has to be set if the mass is. Working
now. Thanks!

On Thursday, August 9, 2012, Joe Spandrusyszyn wrote:

> I did have a similar issue at one point, and found out I was missing
> something... I don't remember what it was though. If you have a simple test
> case to reproduce the issue, I might be able to put in some time to
> investigate it.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/illandril/box2dweb-closure/issues/2#issuecomment-7618559.

## 

## 

Martin Wells
Founder & CEO
Playcraft Labs - getplaycraft.com
